version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.....
      - aws --version
      - docker --version
      - set
      - aws ecr get-login-password --debug
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image....
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images....
      - echo Writing image definitions file...
      
